import { notFound } from "next/navigation";
import { Providers } from "@/app/providers";
import AuthProvider from "@/AuthProvider";
import Header from "@/components/Header";
import { getServerSession } from "next-auth";
import { options } from "../api/auth/[...nextauth]/options";

import "./global.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

const locales = ["vi", "en"];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const session = await getServerSession(options);

  if (!locales.includes(locale)) notFound();
  return (
    <html lang={locale}>
      <body>
        <AuthProvider>
          <Providers>
            <Header locale={locale} />
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
