import { notFound } from "next/navigation";
import { Providers } from "@/app/providers";
import Header from "@/components/Header";
import { getServerSession } from "next-auth";

import "./global.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

const locales = ["vi", "en"];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const session = await getServerSession(options);

  if (!locales.includes(locale)) notFound();
  return (
    <html lang={locale}>
      <body>
        <Providers>
          <Header locale={locale} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
